name: Generate docs

on: push

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nick-mazuk/lua-docs-generator@v1
        with:
          input: './MapMosaic'
          output: './docs'
      - name: Push updated docs
        run: |
          git config user.name CI
          git config user.email "<>"
          git add .
          git diff --quiet HEAD || git commit -m "$GITHUB_SHA"
          git push
